export const capitalize = (string: string): string => {
  const returnString = string
    .split(' ')
    .map((ps) => ps.charAt(0).toUpperCase() + ps.slice(1).toLowerCase());
  return returnString.join(' ');
};

type DataType = {
  countries: string[];
  states: {
    USA: string[];
    Argentina: string[];
    Australia: string[];
    Brazil: string[];
    Canada: string[];
    Mexico: string[];
  };
  getStatesByCountry(country: string): string;
};

export const DATA: DataType = {
  countries: [
    'Mexico',
    'USA',
    'Afghanistan',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarctica',
    'Antigua And Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia And Herzegovina',
    'Botswana',
    'Bouvet Island',
    'Brazil',
    'British Indian Ocean Territory',
    'British Virgin Islands',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Cayman Islands',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos (Keeling) Islands',
    'Colombia',
    'Comoros',
    'Congo',
    'Congo, Democratic Republic Of The',
    'Cook Islands',
    'Costa Rica',
    "Cote d'Ivoire",
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Falkland Islands',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'French Southern Territories',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Heard And Mcdonald Islands',
    'Honduras',
    'Hong Kong SAR',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea, Democratic PeopleS Republic Of',
    'Korea, Republic Of',
    'Kuwait',
    'Kyrgyzstan',
    "Lao People'S Democratic Republic",
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libyan Arab Jamahiriya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macau (San), China',
    'Macedonia (Fyrom)',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Micronesia',
    'Moldova, Republic Of',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands Antilles',
    'Netherlands',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'Northern Ireland',
    'Northern Mariana Islands',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Pitcairn Island',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Reunion',
    'Romania',
    'Russian Federation',
    'Rwanda',
    'Saint Barthelemy',
    'Saint Helena',
    'Saint Kitts And Nevis',
    'Saint Lucia',
    'Saint Martin',
    'Saint Pierre And Miquelon',
    'Saint Vincent And The Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome And Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia And The South Sandwich Islands',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Svalbard & Jan Mayen Island',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syrian Arab Republic',
    'Taiwan',
    'Tajikistan',
    'Tanzania, United Republic Of',
    'Thailand',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad And Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks And Caicos Islands',
    'Tuvalu',
    'U.S. Virgin Islands',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'Uruguay',
    'Us Minor Outlying Islands',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City State',
    'Venezuela',
    'Vietnam',
    'Wallis And Futuna Islands',
    'Western Sahara',
    'Yemen, Republic Of',
    'Zambia',
    'Zimbabwe',
  ],
  states: {
    USA: [
      'West Virginia',
      'Wyoming',
      'Vermont',
      'Washington',
      'Wisconsin',
      'Texas',
      'Utah',
      'Virginia',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Nevada',
      'New York',
      'Ohio',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'North Carolina',
      'North Dakota',
      'Nebraska',
      'Missouri',
      'Mississippi',
      'Montana',
      'Maine',
      'Michigan',
      'Minnesota',
      'Louisiana',
      'Massachusetts',
      'Maryland',
      'Indiana',
      'Kansas',
      'Kentucky',
      'Iowa',
      'Idaho',
      'Illinois',
      'Florida',
      'Georgia',
      'Hawaii',
      'Connecticut',
      'District of Columbia',
      'Delaware',
      'Arizona',
      'California',
      'Colorado',
      'Alaska',
      'Alabama',
      'Arkansas',
      'Rhode Island',
    ],
    Argentina: [
      'Buenos Aires',
      'Catamarca',
      'Chubut',
      'Cordoba',
      'Chaco',
      'Formosa',
      'La Rioja',
      'Mendoza',
      'Misiones',
      'Neuquen',
      'Jujuy',
      'Rio Negro',
      'Salta',
      'Santa Cruz',
      'Santiago del Estero',
      'Santa Fe',
      'San Juan',
      'San Luis',
      'Tucuman',
    ],
    Australia: [
      'Australian Capital Territory',
      'New South Wales',
      'Northern Territory',
      'Queensland',
      'South Australia',
      'Tasmania',
      'Victoria',
      'Western Australia',
    ],
    Brazil: [
      'Acre',
      'Alagoas',
      'Amazonas',
      'Amapa',
      'Bahia',
      'Ceara',
      'Distrito Federal',
      'Espirito Santo',
      'Fernando de Noronha',
      'Goias',
      'Maranhao',
      'Minas Gerais',
      'Mato Grosso do Sul',
      'Mato Grosso',
      'Para',
      'Paraiba',
      'Pernambuco',
      'Piaui',
      'Parana',
      'Rio de Janeiro',
      'Rio Grande do Norte',
      'Rondonia',
      'Roraima',
      'Rio Grande do Sul',
      'Santa Catarina',
      'Sergipe',
      'Sao Paulo',
      'Tocantins',
    ],
    Canada: [
      'Alberta',
      'British Columbia',
      'Manitoba',
      'New Brunswick',
      'Nova Scotia',
      'Northwest Territories',
      'Nunavut',
      'Ontario',
      'Prince Edward Island',
      'Quebec',
      'Saskatchewan',
      'Yukon Territory',
      'Newfoundland and Labrador',
    ],
    Mexico: [
      'Aguascalientes',
      'Baja California',
      'Baja California Sur',
      'Campeche',
      'Coahuila',
      'Colima',
      'Chiapas',
      'Chihuahua',
      'Ciudad de México',
      'Durango',
      'Guanajuato',
      'Guerrero',
      'Hidalgo',
      'Jalisco',
      'México',
      'Michoacán',
      'Morelos',
      'Nayarit',
      'Nuevo León',
      'Oaxaca',
      'Puebla',
      'Querétaro',
      'Quintana Roo',
      'San Luis Potosí',
      'Sinaloa',
      'Sonora',
      'Tabasco',
      'Tamaulipas',
      'Tlaxcala',
      'Veracruz',
      'Yucatán',
      'Zacatecas',
    ],
  },
  getStatesByCountry(country) {
    return this.states[country];
  },
};

export const globalBeforeInsertHook = (userId, doc) => {
  doc.createdAt = new Date();
  doc.createdBy = userId;
  doc.lastUpdatedBy = userId;
  doc.lastUpdatedAt = new Date();
};

export const globalBeforeUpdateHook = (userId, doc, fieldNames, modifier) => {
  if (!userId) return;
  return (modifier['$set'] = {
    ...modifier['$set'],
    lastUpdatedBy: userId,
    lastUpdatedAt: new Date(),
  });
};
